services:
  ionic:
    container_name: web_ionic_DaClin
    build: ./DaClin
    command: ionic serve --host=0.0.0.0 --port=8100
    volumes:
      - .:/code/DaClin
    ports:
      - "8100:8100"
    working_dir: /code/DaClin
    networks:
      - DaClin_net
include:
  - path: ./mongoDB/compose.yaml
  - path: ./fastApi/compose.yaml
networks:
  DaClin_net:
volumes:
  mongodb_DaClin:
  mongodb_config_DaClin:
